const books = [
  {
    id: 1,
    name: "Pride and Prejudice",
    image: "https://example.com/pride_and_prejudice.jpg",
    author: "Jane Austen",
    status: "read",
  },
  {
    id: 2,
    name: "To Kill a Mockingbird",
    image: "https://example.com/to_kill_a_mockingbird.jpg",
    author: "Harper Lee",
    status: "reading",
  },
  {
    id: 3,
    name: "1984",
    image: "https://example.com/1984.jpg",
    author: "George Orwell",
    status: "to be read",
  },
  {
    id: 4,
    name: "Moby-Dick",
    image: "https://example.com/moby_dick.jpg",
    author: "Herman Melville",
    status: "read",
  },
  {
    id: 5,
    name: "The Great Gatsby",
    image: "https://example.com/the_great_gatsby.jpg",
    author: "F. Scott Fitzgerald",
    status: "reading",
  },
  {
    id: 6,
    name: "War and Peace",
    image: "https://example.com/war_and_peace.jpg",
    author: "Leo Tolstoy",
    status: "to be read",
  },
  {
    id: 7,
    name: "Jane Eyre",
    image: "https://example.com/jane_eyre.jpg",
    author: "Charlotte Brontë",
    status: "reading",
  },
  {
    id: 8,
    name: "The Catcher in the Rye",
    image: "https://example.com/the_catcher_in_the_rye.jpg",
    author: "J.D. Salinger",
    status: "to be read",
  },
  {
    id: 9,
    name: "Frankenstein",
    image: "https://example.com/frankenstein.jpg",
    author: "Mary Shelley",
    status: "read",
  },
  {
    id: 10,
    name: "Don Quixote",
    image: "https://example.com/don_quixote.jpg",
    author: "Miguel de Cervantes",
    status: "to be read",
  },
  {
    id: 11,
    name: "To Kill a Mockingbird",
    image: "https://example.com/to_kill_a_mockingbird.jpg",
    author: "Harper Lee",
    status: "reading",
  },
  {
    id: 12,
    name: "The Picture of Dorian Gray",
    image: "https://example.com/dorian_gray.jpg",
    author: "Oscar Wilde",
    status: "to be read",
  },
  {
    id: 13,
    name: "The Scarlet Letter",
    image: "https://example.com/scarlet_letter.jpg",
    author: "Nathaniel Hawthorne",
    status: "read",
  },
  {
    id: 14,
    name: "The Count of Monte Cristo",
    image: "https://example.com/count_of_monte_cristo.jpg",
    author: "Alexandre Dumas",
    status: "to be read",
  },
  {
    id: 15,
    name: "Wuthering Heights",
    image: "https://example.com/wuthering_heights.jpg",
    author: "Emily Brontë",
    status: "reading",
  },
];

export default books;
